# Generated by Django 3.0.4 on 2020-05-04 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200503_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2020, 5, 4), max_length=200),
        ),
    ]
