# Generated by Django 3.0.6 on 2020-05-06 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=200),
        ),
    ]
