# Generated by Django 3.0.4 on 2020-05-11 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200506_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(default='default title', max_length=250)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, max_length=200)),
            ],
        ),
    ]
