# Generated by Django 3.0.4 on 2020-05-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_sudoku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sudoku',
        ),
    ]
